services:
  db:
    image: timescale/timescaledb:2.18.2-pg16
    container_name: stocks_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  ingestion:
    build:
      context: .
      dockerfile: infra/docker/ingestion.Dockerfile
    container_name: stocks_ingestion
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    volumes:
      - .:/app
    command: ["python", "-m", "jobs.ingestion.full_build"]

  training:
    build:
      context: .
      dockerfile: infra/docker/training.Dockerfile
    container_name: stocks_training
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    volumes:
      - .:/app
    command: ["python", "-m", "jobs.training.full_train"]

volumes:
  postgres_data: