MODEL_FEATURE_COLUMNS = [
    "return_1d",
    "return_5d",
    "return_21d",
    "return_63d",
    "return_126d",
    "log_return_1d",
    "price_sma_20_ratio",
    "volatility_21d",
    "volatility_63d",
    "volatility_ratio_21_63",
    "return_21d_over_vol_21d",
    "volume_ratio_20d",
    "avg_daily_volume_20d",
    "avg_daily_traded_value_20d",
    "volume_trend_5_20",
    "traded_value_trend_5_20",
    "high_low_ratio",
    "gap",
    "return_1d_vs_sector",
    "return_5d_vs_sector",
    "return_1d_cs",
    "return_5d_cs",
    "return_21d_cs",
    "return_63d_cs",
    "return_126d_cs",
    "price_sma_20_ratio_cs",
    "volatility_21d_cs",
    "volatility_63d_cs",
    "volume_ratio_20d_cs",
    "avg_daily_volume_20d_cs",
    "avg_daily_traded_value_20d_cs",
    "volume_trend_5_20_cs",
    "traded_value_trend_5_20_cs",
    "high_low_ratio_cs",
    "gap_cs",
    "return_1d_vs_sector_cs",
    "return_5d_vs_sector_cs",
]
EXCLUDED_MODEL_FEATURE_COLUMNS = [
    "momentum_21_63",
    "momentum_5_21",
    "market_cap",
    "price_to_earnings",
    "price_to_book",
    "eps",
    "roe",
    "roa",
    "debt_to_equity",
    "dividend_yield",
    "beta",
    "fifty_two_week_high",
    "fifty_two_week_low",
    "sma20_to_52w_high",
    "sma20_to_52w_low",

    # =========================
    # MARKET FEATURES
    # =========================
    "ibov_return_1d",
    "ibov_return_5d",
    "ibov_return_21d",
    "ibov_return_63d",
    "ibov_vol_21d",
    "ibov_vol_63d",
    "ibov_above_sma_200",

    "sp500_return_1d",
    "sp500_return_5d",
    "sp500_return_21d",
    "sp500_return_63d",
    "sp500_vol_21d",
    "sp500_vol_63d",
    "sp500_above_sma_200",

    "selic_rate",
    "selic_change_21d",
    "selic_change_63d",

    "ipca_12m",

    # =========================
    # MACRO INTERACTIONS
    # =========================
    "return_21d_x_ibov_return_21d",
    "return_63d_x_ibov_return_63d",
    "return_126d_x_ibov_return_63d",
    "momentum_21_63_x_ibov_return_63d",
    "momentum_5_21_x_ibov_return_21d",

    "return_21d_x_sp500_return_21d",
    "return_63d_x_sp500_return_63d",
    "return_126d_x_sp500_return_63d",

    "volatility_21d_x_ibov_vol_21d",
    "volatility_63d_x_ibov_vol_63d",
    "volatility_21d_x_sp500_vol_21d",
    "volatility_63d_x_sp500_vol_63d",

    "return_21d_x_ibov_above_sma_200",
    "return_63d_x_ibov_above_sma_200",
    "momentum_21_63_x_ibov_above_sma_200",
    "volatility_21d_x_ibov_above_sma_200",

    "return_21d_x_selic_change_21d",
    "return_63d_x_selic_change_63d",
    "return_21d_x_ipca_12m",
]